# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# MAOUIDI 2025 STANDARDS - Strict Linting Configuration
# This enforces best practices for Riverpod, performance, and code quality.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

# Enable custom_lint and riverpod_lint analyzers
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - custom_lint
  errors:
    use_build_context_synchronously: ignore
    unused_element: ignore
    deprecated_member_use: ignore

linter:
  rules:
    # ===== PERFORMANCE & OPTIMIZATION =====
    # Enforce const constructors for immutable widgets (reduces rebuilds)
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    # ===== CODE QUALITY =====
    # Enforce key parameter in widget constructors
    use_key_in_widget_constructors: true

    # Encourage immutability
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true

    # Prohibit print statements (use proper logging)
    avoid_print: true

    # Code clarity
    always_declare_return_types: true
    require_trailing_commas: true
    sort_child_properties_last: true

    # ===== RIVERPOD BEST PRACTICES =====
    # These are enforced by riverpod_lint plugin, but we add general rules
    avoid_function_literals_in_foreach_calls: true

    # ===== AVOID COMMON MISTAKES =====
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true

    # ===== STYLE =====
    prefer_single_quotes: true
    unnecessary_string_escapes: false

    # Async/Await safety
    unawaited_futures: true
    use_build_context_synchronously: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
