// lib/core/constants.dart

const List<String> medicalSpecialties = [
  'Anatomy and Pathological Cytology',
  'Cardiology',
  'Dermatology and Venereology',
  'Endocrinology and Diabetology',
  'Epidemiology and Preventive Medicine',
  'Gastroenterology and Hepatology',
  'Hematology (Clinical)',
  'Infectious Diseases',
  'Internal Medicine',
  'Medical Oncology',
  'Nephrology',
  'Neurology',
  'Nuclear Medicine',
  'Pediatrics',
  'Physical Medicine and Rehabilitation',
  'Pneumology',
  'Psychiatry',
  'Radiology / Medical Imaging',
  'Radiotherapy',
  'Rheumatology',
  'Sports Medicine',
  'Anesthesiology and Reanimation',
  'Cardiovascular Surgery',
  'General Surgery',
  'Maxillofacial Surgery',
  'Neurosurgery',
  'Obstetrics and Gynecology',
  'Ophthalmology',
  'Orthopedics and Traumatology',
  'Otorhinolaryngology (ENT)',
  'Pediatric Surgery',
  'Plastic, Reconstructive, and Aesthetic Surgery',
  'Thoracic Surgery',
  'Urology',
  'Vascular Surgery',
  'Biochemistry',
  'Clinical Neurophysiology',
  'Hematology (Biological)',
  'Histology, Embryology, and Cytogenetics',
  'Immunology',
  'Microbiology',
  'Medical Biophysics',
  'Parasitology and Mycology',
  'Pharmacology',
  'Physiology',
  'Toxicology',
  'Child Psychiatry',
  'Community Health / Public Health',
  'Emergency Medicine',
  'Forensic Medicine and Medical Deontology',
  'Occupational Medicine',
  'Stomatology',
  'Transfusion Medicine (Hemobiology)',
];
const List<String> algerianStates = [
  'Adrar',
  'Chlef',
  'Laghouat',
  'Oum El Bouaghi',
  'Batna',
  'Béjaïa',
  'Biskra',
  'Béchar',
  'Blida',
  'Bouira',
  'Tamanrasset',
  'Tébessa',
  'Tlemcen',
  'Tiaret',
  'Tizi Ouzou',
  'Alger',
  'Djelfa',
  'Jijel',
  'Sétif',
  'Saïda',
  'Skikda',
  'Sidi Bel Abbès',
  'Annaba',
  'Guelma',
  'Constantine',
  'Médéa',
  'Mostaganem',
  'M\'Sila',
  'Mascare',
  'Ouargla',
  'Oran',
  'El Bayadh',
  'Illizi',
  'Bordj Bou Arreridj',
  'Boumerdès',
  'El Tarf',
  'Tindouf',
  'Tissemsilt',
  'Oued souf',
  'Khenchela',
  'Souk Ahras',
  'Tipaza',
  'Mila',
  'A\'n Defla',
  'Na\'ama',
  'A\'n Témouchent',
  'Ghardaïa',
  'Relizane',
  'Timimoun',
  'Bordj Badji Mokhtar',
  'Ouled Djellal',
  'Béni Abbès',
  'In Salah',
  'AIn Guezzam',
  'Touggourt',
  'Djanet',
  'El M\'Ghair',
  'El Meniaa',
];
const String defaultAvatarUrl =
    'https://storage.googleapis.com/flutterflow-io-6f20.appspot.com/projects/health-app-j75f2j/assets/7957s72h1p38/avatar-default.png';
